theme: minima
title: Climate Ed Tech toolkit
description: Step by step guide to having discussions at HE about the impact of digital education in the climate emergency.
author: Digital Sustainabilty SIG
<div id="wcb" class="carbonbadge"></div>
<script src="https://unpkg.com/website-carbon-badges@1.1.3/b.min.js" defer></script>
